<a href="https://colab.research.google.com/github/xcellentbird/Study-Deep_Learning/blob/main/%EB%A1%9C%EC%A7%80%EC%8A%A4%ED%8B%B1_%ED%9A%8C%EA%B7%80_%EB%8B%A4%EC%A4%91_%EB%B6%84%EB%A5%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
fish = pd.read_csv('http://bit.ly/fish_csv')

# 5개의 특성이 존재한다.
fish.head()

Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961
3   Bream   363.0    29.0      33.5  12.7300  4.4555
4   Bream   430.0    29.0      34.0  12.4440  5.1340

In [5]:
print(pd.unique(fish['Species']))
# 그리고 7개의 label이 존재

['Bream' 'Roach' 'Whitefish' 'Parkki' 'Perch' 'Pike' 'Smelt']


In [7]:
fish_input = fish[['Weight', 'Length', 'Diagonal', 'Height', 'Width']].to_numpy()
fish_target = fish['Species'].to_numpy()

In [8]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(fish_input, fish_target)

In [9]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

In [10]:
from sklearn.neighbors import KNeighborsClassifier
kn = KNeighborsClassifier(n_neighbors = 3)
kn.fit(train_scaled, train_target)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [19]:
print(kn.predict(test_scaled))
print(test_target)
print(kn.score(test_scaled, test_target))

['Parkki' 'Smelt' 'Perch' 'Bream' 'Roach' 'Roach' 'Roach' 'Roach' 'Perch'
 'Pike' 'Pike' 'Pike' 'Pike' 'Perch' 'Perch' 'Smelt' 'Bream' 'Roach'
 'Smelt' 'Smelt' 'Whitefish' 'Parkki' 'Bream' 'Perch' 'Perch' 'Bream'
 'Bream' 'Perch' 'Parkki' 'Roach' 'Parkki' 'Perch' 'Bream' 'Bream' 'Bream'
 'Perch' 'Parkki' 'Smelt' 'Bream' 'Bream']
['Bream' 'Smelt' 'Perch' 'Bream' 'Perch' 'Parkki' 'Parkki' 'Roach' 'Perch'
 'Pike' 'Pike' 'Pike' 'Pike' 'Perch' 'Perch' 'Smelt' 'Bream' 'Roach'
 'Smelt' 'Perch' 'Perch' 'Parkki' 'Bream' 'Perch' 'Perch' 'Bream' 'Bream'
 'Perch' 'Parkki' 'Roach' 'Parkki' 'Roach' 'Bream' 'Bream' 'Bream' 'Roach'
 'Parkki' 'Smelt' 'Bream' 'Bream']
0.8


In [16]:
import numpy as np

proba = kn.predict_proba(test_scaled)
np.round(proba, decimals=3)

array([[0.333, 0.667, 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 1.   , 0.   ],
       [0.   , 0.   , 0.667, 0.   , 0.   , 0.   , 0.333],
       [1.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.333, 0.   , 0.667, 0.   , 0.   ],
       [0.   , 0.   , 0.333, 0.   , 0.667, 0.   , 0.   ],
       [0.   , 0.   , 0.333, 0.   , 0.667, 0.   , 0.   ],
       [0.   , 0.   , 0.333, 0.   , 0.667, 0.   , 0.   ],
       [0.   , 0.   , 0.667, 0.   , 0.   , 0.333, 0.   ],
       [0.   , 0.   , 0.   , 1.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 1.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 1.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 1.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 1.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.667, 0.   , 0.333, 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 1.   , 0.   ],
       [1.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   ,

In [28]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(C=20, max_iter=1000)
lr.fit(train_scaled, train_target)
train_score = lr.score(train_scaled, train_target)
test_score =lr.score(test_scaled, test_target)

In [31]:
decision = lr.decision_function(test_scaled)

from scipy.special import softmax
proba = softmax(decision, axis = 1)
print(np.round(proba, decimals = 3))

[[0.474 0.414 0.    0.    0.067 0.    0.046]
 [0.    0.002 0.7   0.    0.029 0.268 0.001]
 [0.    0.001 0.886 0.007 0.082 0.    0.024]
 [0.964 0.003 0.    0.    0.001 0.    0.033]
 [0.    0.03  0.537 0.003 0.37  0.002 0.059]
 [0.    0.841 0.009 0.    0.109 0.025 0.017]
 [0.    0.919 0.003 0.    0.058 0.009 0.011]
 [0.    0.042 0.05  0.001 0.881 0.004 0.022]
 [0.    0.008 0.835 0.    0.072 0.081 0.004]
 [0.    0.    0.008 0.991 0.001 0.    0.   ]
 [0.    0.    0.    1.    0.    0.    0.   ]
 [0.    0.    0.002 0.998 0.    0.    0.   ]
 [0.    0.    0.014 0.986 0.    0.    0.   ]
 [0.    0.    0.946 0.    0.002 0.    0.052]
 [0.    0.009 0.785 0.001 0.176 0.016 0.012]
 [0.    0.001 0.051 0.    0.002 0.946 0.   ]
 [1.    0.    0.    0.    0.    0.    0.   ]
 [0.001 0.009 0.284 0.016 0.627 0.001 0.062]
 [0.    0.001 0.11  0.    0.005 0.884 0.   ]
 [0.    0.017 0.538 0.    0.056 0.386 0.003]
 [0.002 0.007 0.654 0.025 0.236 0.    0.077]
 [0.001 0.824 0.006 0.    0.136 0.006 0.027]
 [0.999 0.