In [3]:
import numpy as np

In [30]:
x, c = [[1],[2],[3]], 5

print("더하기 : {}".format(x + c))

TypeError: can only concatenate list (not "int") to list

TypeError: can only concatenate list (not "int") to list  
타입 에러: 리스트는 리스트(int형이 아닌)와 이어질 수 있다.

In [7]:
nx = np.array([1,2,3])
nc = 5

print("더하기 : {}".format(nx + nc))

더하기 : [6 7 8]


numpy를 쓰지 않으면 오류가 나지만, numpy를 쓴 벡터에 상수값을 더하면, 벡터의 각 요소에 상수를 더한 값이 반환된다.
또한 더하기 뿐만 아니라, 빼기, 나누기, 곱하기도 똑같은 원리로 작동한다.

### Vector와 Vector 연산

In [9]:
y = np.array([1, 3, 5])
z = np.array([2, 9, 20])

print("더하기 : {}".format(y+z))
print("빼기  : {}".format(y-z))
print("곱하기 : {}".format(y*z))
print("나누기 : {}".format(y/z))

더하기 : [ 3 12 25]
빼기  : [ -1  -6 -15]
곱하기 : [  2  27 100]
나누기 : [0.5        0.33333333 0.25      ]


np를 사용하여 행렬끼리 사칙연산하면 각 같은 자리의 요소끼리 짝지어 연산되어 반환된다.

### Numpy의 index 요소 접근

In [13]:
W = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

# [col, row] == list의 [col][row]와 같다. 3차원이라면 그 뒤에 이어서 적어주면 된다.
print(W[0, 0])
print(W[2, 3])

1
12


In [15]:
# ex) 두번째 3번째 열의 모든 요소를 가져온다
W[:, 2]

array([ 3,  7, 11])

In [16]:
# 첫번째 행
W[0, :]

array([1, 2, 3, 4])

In [19]:
# 첫번째 행에서 2번째 요소부터 4번째까지
W[0, 1:]

array([2, 3, 4])

In [20]:
W[:, :3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [27]:
b = np.array([[3],[1],[0],[5]])
b

array([[3],
       [1],
       [0],
       [5]])

In [28]:
# 행렬곱
np.matmul(W,b)

array([[25],
       [61],
       [97]])

In [29]:
# 행렬의 MxN이 맞지 않는 경우
W * b

ValueError: operands could not be broadcast together with shapes (3,4) (4,1) 

ValueError: operands could not be broadcast together with shape D1, D2  
값 에러: D1과 D2를 이용한 해당 조작은 이루어질 수 없다.

### Numpy의 Broadcasting

기본적으로 같은 Type의 data에 대해서만 연산이 가능하지만,  
numpy에서는 행렬의 크기가 달라도 연산 가능하도록 만들 수 있습니다.

In [44]:
b1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
b2 = np.array([0,1,29])

b3 = b2[:,None]

print(b1 + b2)
print(b1 + b3)

[[ 1  3 32]
 [ 4  6 35]
 [ 7  9 38]]
[[ 1  2  3]
 [ 5  6  7]
 [36 37 38]]


In [46]:
b2, b3

(array([ 0,  1, 29]),
 array([[ 0],
        [ 1],
        [29]]))

In [47]:
b1 * b2

array([[  0,   2,  87],
       [  0,   5, 174],
       [  0,   8, 261]])

In [48]:
b1 * b3

array([[  0,   0,   0],
       [  4,   5,   6],
       [203, 232, 261]])

In [49]:
t = np.array([1,2,3])[:,None]
u = np.array([2,0,-2])

print(t + u)

[[ 3  1 -1]
 [ 4  2  0]
 [ 5  3  1]]


In [50]:
#영행렬
#np.zeros(v) , v: 정수값 또는 튜플
np.zeros(3)

array([0., 0., 0.])

In [57]:
np.zeros((3, 1))

array([[0.],
       [0.],
       [0.]])

In [58]:
np.zeros((4, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [60]:
#일벡터
np.ones(4)

array([1., 1., 1., 1.])

In [62]:
#단위벡터
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 행렬식
행렬식: 행렬을 대표하는 값 중 하나  
선형변환 과정에서 Vector의 Scaling척도가 된다.

In [65]:
#행렬식
arr = np.array([[2,3],[1,5]])
#7이 나와야한다

np.linalg.det(arr)

7.000000000000001

### 역행렬

In [67]:
arr_inv = np.linalg.inv(arr)
arr_inv

array([[ 0.71428571, -0.42857143],
       [-0.14285714,  0.28571429]])

In [68]:
np.matmul(arr, arr_inv)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [69]:
arr @ arr_inv

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

### 고유값과 고유벡터
: 정방행렬 (nxn) A에 대해서 $Ax = \lambda x$을 만족하는 $\lambda$와 x를 각각 고유벡터와 고유값이라 한다.

In [92]:
arr2 = np.array([[2,0, -1], [1, 1, -3], [-1,0,5]])

In [93]:
eig_val, eig_vec = np.linalg.eig(arr2)
eig_val, eig_vec

(array([1.        , 1.69722436, 5.30277564]),
 array([[ 0.        , -0.9496026 ,  0.23353599],
        [ 1.        , -0.12485651,  0.59205664],
        [ 0.        , -0.28751653, -0.77131697]]))

In [94]:
arr2 @ eig_vec[:,0]

array([0., 1., 0.])

In [95]:
eig_val[0] * eig_vec[:,0]

array([0., 1., 0.])

### Exercise

#### 1. 어떤 벡터가 주어졌을 때, L2 norm을 구하는 함수 get_L2_norm()을 구현하시오
- 매개변수: 1차원 벡터(np.array)
- 반환값: 인자로 주어진 벡터의 L2 Norm값(number)

#### 2. 어떤 행렬이 singular matrix(특이 행렬)인지 확인하는 함수 is_singular()를 구현하시오
- 매개변수: 2차원 벡터(np.array)
- 반환값: 인자로 주어진 벡터가 singular하면 True, Non-singular면 False

In [102]:
import math

In [103]:
def get_L2_norm(arr):
    arr = np.reshape(arr, -1)
    return math.sqrt(sum(map(lambda x:x**2, arr)))

In [105]:
ret = get_L2_norm(np.array([1,3,2,1,1]))
ret

4.0

In [109]:
def is_singular(arr):
    if not np.linalg.det(arr):
        return True
    return False

In [110]:
is_singular([[1,3],[1,3]])

True