## 1. Numpy 시작하기

#### Remind: 리스트

In [1]:
arr = [1, 'tow', 3.9]

print(arr)

[1, 'tow', 3.9]


#### numpy 모듈 불러오기

In [2]:
import numpy as np

### 왜 numpy를 사용해야 할까요?

#### List

In [3]:
L = range(1000)

# %timeit은 jynb에서 사용하는 실행시간을 체크하는 내부 표현이다.
%timeit [i**2 for i in L]

258 µs ± 420 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


#### numpy.array

In [4]:
N = np.arange(1000)
%timeit N**2

822 ns ± 0.212 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


numpy가 훨씬 속도가 빨랐다.

### numpy.array

numpy의 container, array

In [5]:
arr = np.array([1,4,6])
arr

array([1, 4, 6])

In [6]:
arr_2d = np.array([[1,2,5],[5,2,7]])
arr_2d

array([[1, 2, 5],
       [5, 2, 7]])

(x,)식으로 shape이 나올 경우 행백터이다.

In [7]:
arr.shape

(3,)

shape 함수는 y * x | 열 개수 * 행 개수 | j * i

In [12]:
arr_2d.shape

(2, 3)

열벡터는 뒤에 1을 생략하지 않고 표현해준다.

In [15]:
col_arr = np.array([[2],[3],[-1]])

col_arr.shape

(3, 1)

In [16]:
A = np.array([[3,1,1],[1,-2,-1],[1,1,1]])

print(A)
print(np.shape(A))

[[ 3  1  1]
 [ 1 -2 -1]
 [ 1  1  1]]
(3, 3)


## 백터 코딩

In [11]:
b = np.array([4, 1, 2])

print(b)
print(np.shape(b))

[4 1 2]
(3,)


## 역행렬 구하기

In [17]:
A_inv = np.linalg.inv(A)

print(A_inv)
print(np.shape(A_inv))

[[ 5.00000000e-01 -7.40148683e-17 -5.00000000e-01]
 [ 1.00000000e+00 -1.00000000e+00 -2.00000000e+00]
 [-1.50000000e+00  1.00000000e+00  3.50000000e+00]]
(3, 3)


## 역행렬을 이용한 선형시스템 Ax=b의 해 구하기

In [18]:
x2 = np.matmul(A_inv, b)
x2

array([ 1., -1.,  2.])

@는 행렬곱을 나타낸다. np.matmul대신에 사용가능하다

In [19]:
x = A_inv @ b
x

array([ 1., -1.,  2.])