In [1]:
import numpy as np

Ax = b에서 b에 대한 x를 구할 때, 왜 역행렬이 아닌 LU분해 방법을 쓸까?
1. 연산량이 1/3배 적습니다.
2. A의 요소가 0으로 채워지는 만큼 L과 U도 sparse(0으로 채워지는)합니다. 반대로 역행렬은 상관없이 dense합니다. 이것은 L과 U를 저장하는 memory와 A역행렬을 저장하는 memory가 차이가 난다는 것을 알 수 있습니다.

요약, LU분해가 역행렬보다 빠르고 memory도 적게 사용된다.

In [8]:
A = [[3, -7, -2, 2],[-3, 5, 1, 0],[6,-4,0,-5],[-9,5,-5,12]]
A = np.array(A)
A

array([[ 3, -7, -2,  2],
       [-3,  5,  1,  0],
       [ 6, -4,  0, -5],
       [-9,  5, -5, 12]])

LU 분해:
L(lower triangular mat) 행렬은 하삼각행렬입니다.
U(upper triangular mat) 행렬은 상삼각행렬입니다.

1단계
먼저 L의 1열에는 분해하고자하는 행렬 A의 1열에서 (1, 1)의 스케일 만큼 나눠서 대입해줍니다. (1,1)요소는 1이 되어야합니다.
그리고 대각 위치의 요소들은 모두 1로 초기화 시켜줍니다.

L:
[ 3/3,  0,  0,  0],
[-3/3,  0,  0,  0],
[ 6/3,  0,  0,  0],
[-9/3,  0 , 0,  0]]
=>
[ 1,  0,  0,  0],
[-1,  0,  0,  0],
[ 2,  0,  0,  0],
[-3,  0 , 0,  0]]
=>
[ 1,  0,  0,  0],
[-1,  1,  0,  0],
[ 2,  0,  1,  0],
[-3,  0 , 0,  1]]

2단계
U의 1행에는 A의 1행의 요소들을 그대로 가져와줍니다.
U:
[ 3, -7, -2,  2],
[ 0,  0,  0,  0],
[ 0,  0,  0,  0],
[ 0,  0,  0,  0]]

3단계
자, 이제 L과 U, A를 이용하여, 연립방정식을 세우고 나머지 요소를 구하면 됩니다!

[ 3, -7, -2,  2],
[-3,  5,  1,  0],
[ 6, -4,  0, -5],
[-9,  5, -5, 12]]

=

[ 1,  0,  0,  0],
[-1,  1,  0,  0],
[ 2, l1,  1,  0],
[-3, l2, l3,  1]]
matmul
[ 3, -7, -2,  2],
[ 0, u1, u2, u3],
[ 0,  0, u4, u5],
[ 0,  0,  0, u6]]

In [9]:
L = np.array([[1, 0, 0, 0],[-1, 1, 0, 0,], [2, -5, 1, 0], [-3, 8, 3, 1]])
U = np.array([[3, -7, -2, 2],[0, -2, -1, 2], [0, 0, -1, 1], [0, 0, 0, -1]])

#확인
LU_check = L @ U
LU_check

array([[ 3, -7, -2,  2],
       [-3,  5,  1,  0],
       [ 6, -4,  0, -5],
       [-9,  5, -5, 12]])

In [10]:
np.array_equal(LU_check, A)

True

In [11]:
A == LU_check

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [12]:
(A == LU_check).min()

True